### ISSUE TITLE
Quality of Demo

### ISSUE THREAD

**Issue by MorganCZY** [jayneelparekh/sp2si-code#2]
Thanks for this job, but after listening to the demo in your project webpage, lyrics in the synthesized singing voices can't be heard clearly.

**Comment by jayneelparekh** [comment]
Caution: There are outputs of multiple systems on the webpage, some of which our pretty bad. PMTL is the system with overall best outputs. Please make sure you are not just listening to bad outputs. Also use of headphones is recommended so that the differences in output are more clear and volume of audio is appropriate.

Yes you are right that intelligibility is not up to the mark. However, the problem we tackle is inherently more difficult & useful than traditional methods for speech-to-singing which use additional information like template singing or phone-score sync info .  

The system is now forced to learn to identify, transform and synchronize the speech phonemes with the target melody and has no additional information to help out with any of these. As a first work tackling this problem we felt we made reasonable progress. You can checkout the slides and paper for a more detailed discussion on this (available on the project webpage) 

For improved results, you can also checkout a very recent work which has built over our model: https://arxiv.org/abs/2005.13835
Their demo page: https://ericwudayi.github.io/Speech2Singing-DEMO/
